### ISSUE TITLE
Fail on loading kube config (`type 'List<dynamic>' is not a subtype of type 'List<Map<String, String>>?'`)

### ISSUE THREAD

**Issue by MrYoda** [kbterm/kubeterm#21]
### Platform

macOS

### What happened?

When I trying to load kubeconfig from my `~/.kube/config` file it fails with `type 'List<dynamic>' is not a subtype of type 'List<Map<String, String>>?'` error. Config YAML sample:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: base64encoded-cert-data
    server: https://api.cluster.k8s.company.tld:8443
  name: cluster-k8s

contexts:
- context:
    cluster: cluster-k8s
    namespace: service-namespace
    user: user@company.tld
  name: cluster-k8s-user@company.tld

current-context: cluster-k8s-user@company.tld
kind: Config
preferences: {}
users:
- name: user@company.tld
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - supporting
      - kubectl-cred-api
      - --account-name
      - user@company.tld
      command: /usr/local/bin/k8s-util
      env: []
      interactiveMode: IfAvailable
      provideClusterInfo: false

```

### App version

Version 1.4.3 (105) (Kubeterm-v1.4.3-arm64.dmg)

### Cloud provider

Proprietary on-premise k8s
