### ISSUE TITLE
OpenID based cluster auth

### ISSUE THREAD

**Issue by upcFrost** [kbterm/kubeterm#9]
### Platform

Android

### What would you like to be added?

Hi, would it be possible to add an oidc-based auth similar to https://github.com/int128/kubelogin or https://github.com/micahhausler/k8s-oidc-helper?

### Why is this needed?

Oidc-based login is very nice to have if you use Google Workspace, as it removes the hassle of managing certificates

**Comment by daimg** [comment]
Thanks for the request.

Yes, oidc support would be a useful feature. We could plan it in v1.4.1. (v1.4.0 is under developing and will be released soon)

**Comment by daimg** [comment]
v1.4.1 on android has been released.

OIDC can be supported now when importing a kubeconfig with oidc auth-provider. 
For example, following config will enable google auth for cluster:

```yaml
users:
- name: default
  user:
    auth-provider:
      config:
        client-id: <your client id>
        client-secret: < you client secret>
        idp-issuer-url: https://accounts.google.com
        redirect-url: http://localhost:8000
        extra-scopes: email
      name: oidc
```

You may change oidc config in Cluster details page after imported.
